# Generated by Django 5.1.7 on 2026-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'user_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
